### ISSUE TITLE
A syntax error in a crossbow.yaml options block produces a misleading error

### ISSUE THREAD

**Issue by JodiWarren** [Crossbow-js/crossbow#101]
Given an options block like so:

```yaml
options:
  bs:
    proxy: 'website.static', #stray comma here
    otherOption: 'optionValue'
```

Crossbow will return the following error:

```
»  Sorry, there were no watchers available to run
»  x No watchers available
»  - Error Type:  NoWatchersAvailable
»  - Description: You don't have any watchers
»    defined anywhere in your configuration
»  - Documentation: http://crossbow-cli.io/docs/errors/NoWatchersAvailable
```

Ideally, it would have a more relevant error message
