### ISSUE TITLE
give Better error when parent name given, but no child

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow#102]
like symphony console does.

if I have, 
```yaml
  (copy):
    css: '@sh cp js/**/*.css app/design/frontend/Jh/default/web/css'
    out: '@sh docker cp $PHP_CONTAINER:$ROOT_DIR$CB_CLI_TRAILING ./'
    etc:
      description: Copy app/etc from container to HOST (for env vars etc)
      tasks:
        - '@sh docker cp $PHP_CONTAINER:$APP_DIR/etc app'
```

and I run

```sh
$ cb copy
```

show JUST the tasks that could be run, eg: 

```sh
»  copy:css               [ @sh cp js/**/*.css app/design/frontend/Jh/default/web/css ]
»  copy:out               [ @sh docker cp $PHP_CONTAINER:$ROOT_DIR$CB_CLI_TRAILING ./ ]
»  copy:etc               [ @sh docker cp $PHP_CONTAINER:$APP_DIR/etc app ]

```
