### ISSUE TITLE
should support project 'type'

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow#126]
For example, setting a top-level key of `type: npm` should set the following config options automatically - this will make Crossbow an easier replacement for npm-script workflows

```yaml
config:
  bin: node_modules/.bin
  env_file: 
    - filepath: package.json
      prefix: ['npm', 'package']
```
