### ISSUE TITLE
watch options `block` doesn't apply option from global level

### ISSUE THREAD

**Issue by shakyShane** [Crossbow-js/crossbow#99]
The following does apply the 'block' feature to all watchers, even though it's given at the top level
```yaml
watch:
  options:
    block: true
  default:
    '*.json': '@npm sleep 1'
```

It does work on a per-watcher level however

```yaml
watch:
  default:
    options:
      block: true
    '*.json': '@npm sleep 1'
```
